repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        args: [ --line-length=120 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        types: [ file ]
        files: \.(json|myext)$
      - id: check-yaml
        types: [ file ]
        files: \.(yaml|yml)$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
